#!/bin/sh

. /etc/init.d/functions

pidfile=/var/run/zebra2-webserver.pid

do_start()
{
    procServ -c /opt/share/webserver -n zebra2-webserver \
        -p $pidfile -L /var/log/zebra2-webserver 8023 \
        /usr/bin/python /opt/bin/zebra2-webserver.py --port=80
}

do_stop()
{
    kill $(cat /var/run/zebra2-webserver.pid)
}

do_start_stop "$1" zebra2-webserver
