name: Docs CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Use container from ghcr
    container: 
      image: ghcr.io/pandablocks/pandablocks-dev-container:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes: 
        - ${{ github.workspace }}:/repos
        - ${{ github.workspace }}/build:/build

    steps:
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-webcontrol
          # require history to get back to last tag for version number of branches
          fetch-depth: 0

      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v2
        with:
          repository: PandABlocks/PandABlocks-rootfs
          path: PandABlocks-rootfs

      # Build
      - name: Build Docs
        run: |
          cd PandABlocks-webcontrol
          make docs

      - name: Move to versioned directory
        # e.g. master or 0.1.2
        run: mv PandABlocks-webcontrol/build/malcolmjs_docs/html "PandABlocks-webcontrol/.github/pages/${GITHUB_REF##*/}"

      - name: Publish Docs to gh-pages
        # Only master and tags are published
        if: "${{ github.repository_owner == 'PandABlocks' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}"
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: PandABlocks-webcontrol/.github/pages
          keep_files: true
